from __future__ import annotations

from enum import Enum


class ConnectorType(str, Enum):
    TALLY = "tally"
    BUSY = "busy"
    MARG = "marg"
    MUNIM = "munim"
    ZOHO = "zoho"
    QUICKBOOKS = "quickbooks"
    XERO = "xero"
    FRESHBOOKS = "freshbooks"
    WAVE = "wave"
    NETSUITE = "netsuite"
    DYNAMICS_365 = "dynamics_365"
    SAGE = "sage"
    ODOO = "odoo"
    SAP = "sap"
    ORACLE = "oracle"
    RAZORPAY = "razorpay"
    STRIPE = "stripe"
    AA_FRAMEWORK = "aa_framework"
    PLAID = "plaid"
    KEKA = "keka"
    DARWINBOX = "darwinbox"
    RAZORPAY_PAYROLL = "razorpay_payroll"
    GENERIC_FILE = "generic_file"


class DatasetType(str, Enum):
    TRIAL_BALANCE = "trial_balance"
    GENERAL_LEDGER = "general_ledger"
    PROFIT_AND_LOSS = "profit_and_loss"
    BALANCE_SHEET = "balance_sheet"
    CASH_FLOW_STATEMENT = "cash_flow_statement"
    ACCOUNTS_RECEIVABLE = "accounts_receivable"
    ACCOUNTS_PAYABLE = "accounts_payable"
    AR_AGEING = "ar_ageing"
    AP_AGEING = "ap_ageing"
    FIXED_ASSET_REGISTER = "fixed_asset_register"
    PREPAID_REGISTER = "prepaid_register"
    INVOICE_REGISTER = "invoice_register"
    PURCHASE_REGISTER = "purchase_register"
    CREDIT_NOTE_REGISTER = "credit_note_register"
    DEBIT_NOTE_REGISTER = "debit_note_register"
    SALES_ORDER_REGISTER = "sales_order_register"
    PURCHASE_ORDER_REGISTER = "purchase_order_register"
    BANK_STATEMENT = "bank_statement"
    BANK_TRANSACTION_REGISTER = "bank_transaction_register"
    INVENTORY_REGISTER = "inventory_register"
    INVENTORY_MOVEMENT = "inventory_movement"
    PAYROLL_SUMMARY = "payroll_summary"
    EXPENSE_CLAIMS = "expense_claims"
    TAX_LEDGER = "tax_ledger"
    TDS_REGISTER = "tds_register"
    GST_RETURN_GSTR1 = "gst_return_gstr1"
    GST_RETURN_GSTR2A = "gst_return_gstr2a"
    GST_RETURN_GSTR2B = "gst_return_gstr2b"
    GST_RETURN_GSTR3B = "gst_return_gstr3b"
    EINVOICE_REGISTER = "einvoice_register"
    GST_RETURN_GSTR9 = "gst_return_gstr9"
    GST_RETURN_GSTR9C = "gst_return_gstr9c"
    FORM_26AS = "form_26as"
    AIS_REGISTER = "ais_register"
    STAFF_ADVANCES = "staff_advances"
    VENDOR_ADVANCES = "vendor_advances"
    CUSTOMER_ADVANCES = "customer_advances"
    INTERCOMPANY_TRANSACTIONS = "intercompany_transactions"
    BUDGET_DATA = "budget_data"
    PROJECT_LEDGER = "project_ledger"
    CONTRACT_REGISTER = "contract_register"
    OPENING_BALANCES = "opening_balances"
    SYNC_RECONCILIATION_SUMMARY = "sync_reconciliation_summary"
    CHART_OF_ACCOUNTS = "chart_of_accounts"
    VENDOR_MASTER = "vendor_master"
    CUSTOMER_MASTER = "customer_master"
    DIMENSION_MASTER = "dimension_master"
    CURRENCY_MASTER = "currency_master"


class PeriodGranularity(str, Enum):
    MONTHLY = "monthly"
    QUARTERLY = "quarterly"
    YEARLY = "yearly"
    CUSTOM = "custom"
    AS_AT = "as_at"
    NO_PERIOD = "no_period"


class SyncRunStatus(str, Enum):
    CREATED = "created"
    RUNNING = "running"
    HALTED = "halted"
    FAILED = "failed"
    COMPLETED = "completed"
    PUBLISHED = "published"
    PAUSED = "paused"
    DRIFT_ALERT = "drift_alert"


class DriftSeverity(str, Enum):
    NONE = "none"
    MINOR = "minor"
    SIGNIFICANT = "significant"
    CRITICAL = "critical"
