from __future__ import annotations

from financeops.observability.ai_metrics import observe_ai_cost, observe_ai_tokens
from financeops.observability.business_metrics import (
    active_tenants_gauge,
    ai_anomaly_generation_counter,
    ai_cache_hit_counter,
    ai_cost_counter,
    ai_fallback_counter,
    ai_narrative_duration_ms,
    ai_recommendation_failures_counter,
    ai_pipeline_duration_histogram,
    ai_tokens_counter,
    api_error_counter,
    api_request_counter,
    api_request_latency_ms,
    close_checklist_blockers_gauge,
    close_readiness_failures_counter,
    credits_consumed_counter,
    credits_reserved_gauge,
    auth_failure_counter,
    upload_validation_failure_counter,
    erp_sync_duration_ms,
    erp_sync_counter,
    erp_sync_records_counter,
    finance_workflow_counter,
    finance_workflow_duration_ms,
    governance_operation_counter,
    task_duration_histogram,
    task_queue_depth_gauge,
    tenant_registrations_counter,
    workflow_completed_counter,
    workflow_started_counter,
)

__all__ = [
    "active_tenants_gauge",
    "tenant_registrations_counter",
    "credits_consumed_counter",
    "credits_reserved_gauge",
    "api_request_counter",
    "api_error_counter",
    "api_request_latency_ms",
    "finance_workflow_duration_ms",
    "finance_workflow_counter",
    "erp_sync_duration_ms",
    "governance_operation_counter",
    "close_readiness_failures_counter",
    "close_checklist_blockers_gauge",
    "auth_failure_counter",
    "upload_validation_failure_counter",
    "ai_anomaly_generation_counter",
    "ai_narrative_duration_ms",
    "ai_recommendation_failures_counter",
    "ai_cost_counter",
    "ai_tokens_counter",
    "ai_pipeline_duration_histogram",
    "ai_fallback_counter",
    "ai_cache_hit_counter",
    "task_queue_depth_gauge",
    "task_duration_histogram",
    "erp_sync_counter",
    "erp_sync_records_counter",
    "workflow_started_counter",
    "workflow_completed_counter",
    "observe_ai_cost",
    "observe_ai_tokens",
]
