from __future__ import annotations


SOFTWARE_SAAS_LEDGER_ACCOUNTS: list[dict[str, str]] = [
    {"category": "EQUITY_RESERVES", "name": "Equity Share Capital"},
    {"category": "EQUITY_RESERVES", "name": "Securities Premium"},
    {"category": "EQUITY_RESERVES", "name": "Retained Earnings"},
    {"category": "EQUITY_RESERVES", "name": "General Reserve"},
    {"category": "EQUITY_RESERVES", "name": "OCI Reserve (FVOCI instruments)"},
    {"category": "LONG_TERM_BORROWINGS", "name": "Term Loans - Banks"},
    {"category": "LONG_TERM_BORROWINGS", "name": "Term Loans - NBFCs"},
    {"category": "LONG_TERM_BORROWINGS", "name": "Debentures / Bonds"},
    {"category": "LONG_TERM_BORROWINGS", "name": "Loans from Directors"},
    {"category": "LONG_TERM_BORROWINGS", "name": "Loans from Related Parties"},
    {"category": "LONG_TERM_BORROWINGS", "name": "Vehicle Loans"},
    {"category": "LONG_TERM_BORROWINGS", "name": "Equipment Finance"},
    {"category": "SHORT_TERM_BORROWINGS", "name": "Working Capital Loans - Banks"},
    {"category": "SHORT_TERM_BORROWINGS", "name": "Cash Credit / Overdraft"},
    {"category": "SHORT_TERM_BORROWINGS", "name": "Commercial Paper"},
    {"category": "TRADE_PAYABLES", "name": "Creditors - MSME"},
    {"category": "TRADE_PAYABLES", "name": "Creditors - Others"},
    {"category": "TRADE_PAYABLES", "name": "Accrued Expenses"},
    {"category": "TRADE_PAYABLES", "name": "Advance from Customers (deferred revenue)"},
    {"category": "OTHER_CURRENT_LIABILITIES", "name": "TDS Payable"},
    {"category": "OTHER_CURRENT_LIABILITIES", "name": "GST Payable - CGST"},
    {"category": "OTHER_CURRENT_LIABILITIES", "name": "GST Payable - SGST"},
    {"category": "OTHER_CURRENT_LIABILITIES", "name": "GST Payable - IGST"},
    {"category": "OTHER_CURRENT_LIABILITIES", "name": "Professional Tax Payable"},
    {"category": "OTHER_CURRENT_LIABILITIES", "name": "PF Payable"},
    {"category": "OTHER_CURRENT_LIABILITIES", "name": "ESI Payable"},
    {"category": "OTHER_CURRENT_LIABILITIES", "name": "Salary Payable"},
    {"category": "OTHER_CURRENT_LIABILITIES", "name": "Bonus Payable"},
    {"category": "OTHER_CURRENT_LIABILITIES", "name": "Gratuity Payable (current portion)"},
    {"category": "OTHER_CURRENT_LIABILITIES", "name": "Provision for Income Tax"},
    {"category": "OTHER_CURRENT_LIABILITIES", "name": "Dividend Payable"},
    {"category": "OTHER_CURRENT_LIABILITIES", "name": "Other Statutory Liabilities"},
    {"category": "TANGIBLE_ASSETS", "name": "Leasehold Land"},
    {"category": "TANGIBLE_ASSETS", "name": "Freehold Land"},
    {"category": "TANGIBLE_ASSETS", "name": "Buildings - Owned"},
    {"category": "TANGIBLE_ASSETS", "name": "Buildings - Leasehold Improvements"},
    {"category": "TANGIBLE_ASSETS", "name": "Plant & Machinery"},
    {"category": "TANGIBLE_ASSETS", "name": "Computer Hardware - Servers"},
    {"category": "TANGIBLE_ASSETS", "name": "Computer Hardware - Laptops & Desktops"},
    {"category": "TANGIBLE_ASSETS", "name": "Networking Equipment"},
    {"category": "TANGIBLE_ASSETS", "name": "Furniture & Fixtures"},
    {"category": "TANGIBLE_ASSETS", "name": "Office Equipment"},
    {"category": "TANGIBLE_ASSETS", "name": "Air Conditioning"},
    {"category": "TANGIBLE_ASSETS", "name": "Vehicles"},
    {"category": "TANGIBLE_ASSETS", "name": "Right-of-Use Assets (IFRS 16)"},
    {"category": "TANGIBLE_ASSETS", "name": "Acc. Depreciation - Tangible Assets"},
    {"category": "INTANGIBLE_ASSETS", "name": "Goodwill on Acquisition"},
    {"category": "INTANGIBLE_ASSETS", "name": "Software Licences - Perpetual"},
    {"category": "INTANGIBLE_ASSETS", "name": "Internally Developed Software (capitalised)"},
    {"category": "INTANGIBLE_ASSETS", "name": "Customer Relationships (acquired)"},
    {"category": "INTANGIBLE_ASSETS", "name": "Non-Compete Agreements"},
    {"category": "INTANGIBLE_ASSETS", "name": "Domain Names & IP"},
    {"category": "INTANGIBLE_ASSETS", "name": "Trademarks & Patents"},
    {"category": "INTANGIBLE_ASSETS", "name": "Acc. Amortisation - Intangible Assets"},
    {"category": "CAPITAL_WIP", "name": "Capital Work-in-Progress"},
    {"category": "NON_CURRENT_INVESTMENTS", "name": "Investment in Subsidiaries (at cost)"},
    {"category": "NON_CURRENT_INVESTMENTS", "name": "Investment in Associates (equity method)"},
    {"category": "NON_CURRENT_INVESTMENTS", "name": "Investment in JVs"},
    {"category": "NON_CURRENT_INVESTMENTS", "name": "Investment in Mutual Funds (FVTPL)"},
    {"category": "NON_CURRENT_INVESTMENTS", "name": "Investment in Bonds (FVOCI)"},
    {"category": "NON_CURRENT_INVESTMENTS", "name": "Investment in Quoted Equity (FVTPL)"},
    {"category": "LONG_TERM_LOANS_ADVANCES", "name": "Security Deposits - Office Rent"},
    {"category": "LONG_TERM_LOANS_ADVANCES", "name": "Security Deposits - Utilities"},
    {"category": "LONG_TERM_LOANS_ADVANCES", "name": "Advance Tax (non-current)"},
    {"category": "LONG_TERM_LOANS_ADVANCES", "name": "MAT Credit Entitlement"},
    {"category": "LONG_TERM_LOANS_ADVANCES", "name": "Deferred Tax Assets"},
    {"category": "CURRENT_INVESTMENTS", "name": "Liquid Mutual Funds (FVTPL)"},
    {"category": "CURRENT_INVESTMENTS", "name": "Fixed Deposits (< 1 year)"},
    {"category": "INVENTORIES", "name": "Consumables"},
    {"category": "INVENTORIES", "name": "Printed Materials / Merchandise"},
    {"category": "TRADE_RECEIVABLES", "name": "Debtors - Domestic (< 6 months)"},
    {"category": "TRADE_RECEIVABLES", "name": "Debtors - Domestic (> 6 months)"},
    {"category": "TRADE_RECEIVABLES", "name": "Debtors - Export"},
    {"category": "TRADE_RECEIVABLES", "name": "Unbilled Revenue"},
    {"category": "TRADE_RECEIVABLES", "name": "Allowance for Doubtful Debts (contra)"},
    {"category": "CASH_EQUIVALENTS", "name": "Cash in Hand"},
    {"category": "CASH_EQUIVALENTS", "name": "Current Account - Bank 1"},
    {"category": "CASH_EQUIVALENTS", "name": "Current Account - Bank 2"},
    {"category": "CASH_EQUIVALENTS", "name": "EEFC Account"},
    {"category": "CASH_EQUIVALENTS", "name": "Petty Cash"},
    {"category": "SHORT_TERM_LOANS_ADVANCES", "name": "Advance to Vendors"},
    {"category": "SHORT_TERM_LOANS_ADVANCES", "name": "Advance to Employees"},
    {"category": "SHORT_TERM_LOANS_ADVANCES", "name": "Prepaid Expenses - Insurance"},
    {"category": "SHORT_TERM_LOANS_ADVANCES", "name": "Prepaid Expenses - Subscriptions"},
    {"category": "SHORT_TERM_LOANS_ADVANCES", "name": "Prepaid Expenses - Rent"},
    {"category": "SHORT_TERM_LOANS_ADVANCES", "name": "Prepaid Expenses - Maintenance"},
    {"category": "SHORT_TERM_LOANS_ADVANCES", "name": "GST Input Credit - CGST"},
    {"category": "SHORT_TERM_LOANS_ADVANCES", "name": "GST Input Credit - SGST"},
    {"category": "SHORT_TERM_LOANS_ADVANCES", "name": "GST Input Credit - IGST"},
    {"category": "SHORT_TERM_LOANS_ADVANCES", "name": "Advance Tax (current year)"},
    {"category": "SHORT_TERM_LOANS_ADVANCES", "name": "TDS Receivable"},
    {"category": "REVENUE", "name": "SaaS Subscription Revenue - Annual"},
    {"category": "REVENUE", "name": "SaaS Subscription Revenue - Monthly"},
    {"category": "REVENUE", "name": "Professional Services Revenue"},
    {"category": "REVENUE", "name": "Implementation / Onboarding Revenue"},
    {"category": "REVENUE", "name": "Training Revenue"},
    {"category": "REVENUE", "name": "Marketplace Commission Revenue"},
    {"category": "REVENUE", "name": "API Usage Revenue"},
    {"category": "REVENUE", "name": "Support & Maintenance Revenue"},
    {"category": "REVENUE", "name": "Revenue from Sale of Licences"},
    {"category": "REVENUE", "name": "Export of Services (LUT / IGST)"},
    {"category": "REVENUE", "name": "Other Operating Revenue"},
    {"category": "OTHER_INCOME", "name": "Interest Income - FDs"},
    {"category": "OTHER_INCOME", "name": "Interest Income - Others"},
    {"category": "OTHER_INCOME", "name": "Dividend Income"},
    {"category": "OTHER_INCOME", "name": "Profit on Sale of Investments"},
    {"category": "OTHER_INCOME", "name": "FX Gain (Realised)"},
    {"category": "OTHER_INCOME", "name": "FX Gain (Unrealised)"},
    {"category": "OTHER_INCOME", "name": "Miscellaneous Income"},
    {"category": "OTHER_INCOME", "name": "Insurance Claims Received"},
    {"category": "COGS", "name": "Cloud Infrastructure - AWS/GCP/Azure"},
    {"category": "COGS", "name": "Third-party API & Data Costs"},
    {"category": "COGS", "name": "Payment Gateway Charges"},
    {"category": "COGS", "name": "Software Licences (COGS)"},
    {"category": "COGS", "name": "Contractor / Freelancer Costs (billable)"},
    {"category": "COGS", "name": "Revenue Share - Partners"},
    {"category": "EMPLOYEE_BENEFITS", "name": "Salaries - Engineering"},
    {"category": "EMPLOYEE_BENEFITS", "name": "Salaries - Product"},
    {"category": "EMPLOYEE_BENEFITS", "name": "Salaries - Sales"},
    {"category": "EMPLOYEE_BENEFITS", "name": "Salaries - Customer Success"},
    {"category": "EMPLOYEE_BENEFITS", "name": "Salaries - Finance & Admin"},
    {"category": "EMPLOYEE_BENEFITS", "name": "Salaries - Leadership"},
    {"category": "EMPLOYEE_BENEFITS", "name": "Bonus & Incentives"},
    {"category": "EMPLOYEE_BENEFITS", "name": "ESOP Expense (non-cash)"},
    {"category": "EMPLOYEE_BENEFITS", "name": "PF - Employer Contribution"},
    {"category": "EMPLOYEE_BENEFITS", "name": "ESI - Employer Contribution"},
    {"category": "EMPLOYEE_BENEFITS", "name": "Gratuity - Provision"},
    {"category": "EMPLOYEE_BENEFITS", "name": "Leave Encashment - Provision"},
    {"category": "EMPLOYEE_BENEFITS", "name": "Staff Welfare"},
    {"category": "EMPLOYEE_BENEFITS", "name": "Recruitment Costs"},
    {"category": "EMPLOYEE_BENEFITS", "name": "Training & Development"},
    {"category": "FINANCE_COSTS", "name": "Interest on Term Loans"},
    {"category": "FINANCE_COSTS", "name": "Interest on Working Capital"},
    {"category": "FINANCE_COSTS", "name": "Interest on Lease Liabilities (IFRS 16)"},
    {"category": "FINANCE_COSTS", "name": "Bank Charges & Processing Fees"},
    {"category": "FINANCE_COSTS", "name": "Loan Processing Fees (amortised)"},
    {"category": "FINANCE_COSTS", "name": "FX Loss (Realised)"},
    {"category": "FINANCE_COSTS", "name": "FX Loss (Unrealised)"},
    {"category": "DEPRECIATION_AMORTISATION", "name": "Depreciation - Tangible Assets"},
    {"category": "DEPRECIATION_AMORTISATION", "name": "Amortisation - Intangible Assets"},
    {"category": "DEPRECIATION_AMORTISATION", "name": "Depreciation - ROU Assets (IFRS 16)"},
    {"category": "OTHER_EXPENSES", "name": "Rent (legacy - pre IFRS 16)"},
    {"category": "OTHER_EXPENSES", "name": "Electricity & Utilities"},
    {"category": "OTHER_EXPENSES", "name": "Internet & Connectivity"},
    {"category": "OTHER_EXPENSES", "name": "Office Maintenance"},
    {"category": "OTHER_EXPENSES", "name": "Repairs & Maintenance - Equipment"},
    {"category": "OTHER_EXPENSES", "name": "Insurance - Office"},
    {"category": "OTHER_EXPENSES", "name": "Insurance - D&O"},
    {"category": "OTHER_EXPENSES", "name": "Insurance - Cyber"},
    {"category": "OTHER_EXPENSES", "name": "Legal & Professional Fees"},
    {"category": "OTHER_EXPENSES", "name": "Audit Fees - Statutory"},
    {"category": "OTHER_EXPENSES", "name": "Audit Fees - Internal"},
    {"category": "OTHER_EXPENSES", "name": "ROC Filing Fees"},
    {"category": "OTHER_EXPENSES", "name": "Secretarial Fees"},
    {"category": "OTHER_EXPENSES", "name": "Advertisement & Marketing"},
    {"category": "OTHER_EXPENSES", "name": "Sales Promotion"},
    {"category": "OTHER_EXPENSES", "name": "Travel & Conveyance - Domestic"},
    {"category": "OTHER_EXPENSES", "name": "Travel & Conveyance - International"},
    {"category": "OTHER_EXPENSES", "name": "Visa & Immigration"},
    {"category": "OTHER_EXPENSES", "name": "Printing & Stationery"},
    {"category": "OTHER_EXPENSES", "name": "Telephone & Mobile"},
    {"category": "OTHER_EXPENSES", "name": "Subscriptions - Software Tools"},
    {"category": "OTHER_EXPENSES", "name": "Subscriptions - Industry Bodies"},
    {"category": "OTHER_EXPENSES", "name": "Conference & Events"},
    {"category": "OTHER_EXPENSES", "name": "Bad Debts Written Off"},
    {"category": "OTHER_EXPENSES", "name": "Provision for Doubtful Debts"},
    {"category": "OTHER_EXPENSES", "name": "CSR Expenses"},
    {"category": "OTHER_EXPENSES", "name": "Director Sitting Fees"},
    {"category": "OTHER_EXPENSES", "name": "Commission to Non-Executive Directors"},
    {"category": "OTHER_EXPENSES", "name": "Miscellaneous Expenses"},
    {"category": "TAX", "name": "Current Tax - Income Tax"},
    {"category": "TAX", "name": "Deferred Tax - Charge / (Credit)"},
    {"category": "TAX", "name": "MAT / AMT Charge"},
    {"category": "TAX", "name": "Tax Adjustments (Prior Years)"},
    {"category": "OCI", "name": "Remeasurement of Defined Benefit Plans"},
    {"category": "OCI", "name": "FX Translation Differences (subsidiaries)"},
    {"category": "OCI", "name": "Unrealised Gain/Loss on FVOCI Instruments"},
]
