from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "ReportDefinition",
    "ReportRun",
    "ReportResult",
    "BoardPackGeneratorRun",
    "BoardPackGeneratorDefinition",
    "BoardPackGeneratorSection",
    "BoardPackGeneratorArtifact",
    "DeliverySchedule",
    "DeliveryLog",
    "PipelineRun",
    "PipelineStepLog",
    "OnboardingState",
    "SecretRotationLog",
    "UserPiiKey",
    "ErasureLog",
    "ComplianceControl",
    "ComplianceEvent",
    "GDPRConsentRecord",
    "GDPRDataRequest",
    "GDPRBreachRecord",
    "BackupRunLog",
    "AICostEvent",
    "TenantTokenBudget",
    "ChecklistTemplate",
    "ChecklistTemplateTask",
    "ChecklistRun",
    "ChecklistRunTask",
    "WCSnapshot",
    "ARLineItem",
    "APLineItem",
    "ExpensePolicy",
    "ExpenseClaim",
    "ExpenseApproval",
    "BudgetVersion",
    "BudgetLineItem",
    "ForecastRun",
    "ForecastAssumption",
    "ForecastLineItem",
    "ScenarioSet",
    "ScenarioDefinition",
    "ScenarioResult",
    "ScenarioLineItem",
    "FDDEngagement",
    "FDDSection",
    "FDDFinding",
    "PPAEngagement",
    "PPAAllocation",
    "PPAIntangible",
    "MAWorkspace",
    "MAWorkspaceMember",
    "MAValuation",
    "MADDItem",
    "MADocument",
    "ModuleRegistry",
    "TaskRegistry",
    "MarketplaceContributor",
    "MarketplaceTemplate",
    "MarketplacePurchase",
    "MarketplacePayout",
    "MarketplaceRating",
    "WhiteLabelConfig",
    "WhiteLabelAuditLog",
    "PartnerProfile",
    "ReferralTracking",
    "PartnerCommission",
    "NotificationEvent",
    "NotificationReadState",
    "NotificationPreferences",
    "LearningSignal",
    "LearningCorrection",
    "AIBenchmarkResult",
    "SearchIndexEntry",
    "CashFlowForecastRun",
    "CashFlowForecastAssumption",
    "TaxProvisionRun",
    "TaxPosition",
    "CovenantDefinition",
    "CovenantBreachEvent",
    "TPConfig",
    "ICTransaction",
    "TransferPricingDoc",
    "DirectorSignoff",
    "StatutoryRegisterEntry",
    "StatutoryFiling",
    "MultiGAAPConfig",
    "MultiGAAPRun",
    "AuditorPortalAccess",
    "AuditorRequest",
    "MfaRecoveryCode",
    "PasswordResetToken",
    "AccountingJVAggregate",
    "AccountingJVLine",
    "AccountingJVStateEvent",
    "AccountingJVApproval",
    "ApprovalSLATimer",
    "AccountingVendor",
    "AccountingAttachment",
    "ErpAttachmentLink",
    "AccountingDuplicateFingerprint",
    "ErpAccountExternalRef",
    "AccountingGSTRule",
    "AccountingTDSRule",
    "AccountingTaxDeterminationLog",
    "ErpPushRun",
    "ErpPushEvent",
    "ErpPushIdempotencyKey",
    "ErpWebhookEvent",
    "AccountingInboundEmailMessage",
    "VendorPortalSubmission",
    "AccountingNotificationEvent",
    "ApprovalReminderRun",
    "AccountingAPAgeingSnapshot",
    "AccountingAuditExportRun",
]

_MODEL_IMPORTS: dict[str, tuple[str, str]] = {
    "ReportDefinition": ("financeops.db.models.custom_report_builder", "ReportDefinition"),
    "ReportRun": ("financeops.db.models.custom_report_builder", "ReportRun"),
    "ReportResult": ("financeops.db.models.custom_report_builder", "ReportResult"),
    "BoardPackGeneratorRun": (
        "financeops.db.models.board_pack_generator",
        "BoardPackGeneratorRun",
    ),
    "BoardPackGeneratorDefinition": (
        "financeops.db.models.board_pack_generator",
        "BoardPackGeneratorDefinition",
    ),
    "BoardPackGeneratorSection": (
        "financeops.db.models.board_pack_generator",
        "BoardPackGeneratorSection",
    ),
    "BoardPackGeneratorArtifact": (
        "financeops.db.models.board_pack_generator",
        "BoardPackGeneratorArtifact",
    ),
    "DeliverySchedule": ("financeops.db.models.scheduled_delivery", "DeliverySchedule"),
    "DeliveryLog": ("financeops.db.models.scheduled_delivery", "DeliveryLog"),
    "PipelineRun": ("financeops.modules.auto_trigger.models", "PipelineRun"),
    "PipelineStepLog": ("financeops.modules.auto_trigger.models", "PipelineStepLog"),
    "OnboardingState": ("financeops.modules.template_onboarding.models", "OnboardingState"),
    "SecretRotationLog": ("financeops.modules.secret_rotation.models", "SecretRotationLog"),
    "UserPiiKey": ("financeops.modules.compliance.models", "UserPiiKey"),
    "ErasureLog": ("financeops.modules.compliance.models", "ErasureLog"),
    "ComplianceControl": ("financeops.modules.compliance.models", "ComplianceControl"),
    "ComplianceEvent": ("financeops.modules.compliance.models", "ComplianceEvent"),
    "GDPRConsentRecord": ("financeops.modules.compliance.gdpr_models", "GDPRConsentRecord"),
    "GDPRDataRequest": ("financeops.modules.compliance.gdpr_models", "GDPRDataRequest"),
    "GDPRBreachRecord": ("financeops.modules.compliance.gdpr_models", "GDPRBreachRecord"),
    "BackupRunLog": ("financeops.modules.backup.models", "BackupRunLog"),
    "AICostEvent": ("financeops.db.models.ai_cost", "AICostEvent"),
    "TenantTokenBudget": ("financeops.db.models.ai_cost", "TenantTokenBudget"),
    "ChecklistTemplate": ("financeops.modules.closing_checklist.models", "ChecklistTemplate"),
    "ChecklistTemplateTask": ("financeops.modules.closing_checklist.models", "ChecklistTemplateTask"),
    "ChecklistRun": ("financeops.modules.closing_checklist.models", "ChecklistRun"),
    "ChecklistRunTask": ("financeops.modules.closing_checklist.models", "ChecklistRunTask"),
    "WCSnapshot": ("financeops.modules.working_capital.models", "WCSnapshot"),
    "ARLineItem": ("financeops.modules.working_capital.models", "ARLineItem"),
    "APLineItem": ("financeops.modules.working_capital.models", "APLineItem"),
    "ExpensePolicy": ("financeops.modules.expense_management.models", "ExpensePolicy"),
    "ExpenseClaim": ("financeops.modules.expense_management.models", "ExpenseClaim"),
    "ExpenseApproval": ("financeops.modules.expense_management.models", "ExpenseApproval"),
    "BudgetVersion": ("financeops.modules.budgeting.models", "BudgetVersion"),
    "BudgetLineItem": ("financeops.modules.budgeting.models", "BudgetLineItem"),
    "ForecastRun": ("financeops.modules.forecasting.models", "ForecastRun"),
    "ForecastAssumption": ("financeops.modules.forecasting.models", "ForecastAssumption"),
    "ForecastLineItem": ("financeops.modules.forecasting.models", "ForecastLineItem"),
    "ScenarioSet": ("financeops.modules.scenario_modelling.models", "ScenarioSet"),
    "ScenarioDefinition": ("financeops.modules.scenario_modelling.models", "ScenarioDefinition"),
    "ScenarioResult": ("financeops.modules.scenario_modelling.models", "ScenarioResult"),
    "ScenarioLineItem": ("financeops.modules.scenario_modelling.models", "ScenarioLineItem"),
    "FDDEngagement": ("financeops.modules.fdd.models", "FDDEngagement"),
    "FDDSection": ("financeops.modules.fdd.models", "FDDSection"),
    "FDDFinding": ("financeops.modules.fdd.models", "FDDFinding"),
    "PPAEngagement": ("financeops.modules.ppa.models", "PPAEngagement"),
    "PPAAllocation": ("financeops.modules.ppa.models", "PPAAllocation"),
    "PPAIntangible": ("financeops.modules.ppa.models", "PPAIntangible"),
    "MAWorkspace": ("financeops.modules.ma_workspace.models", "MAWorkspace"),
    "MAWorkspaceMember": ("financeops.modules.ma_workspace.models", "MAWorkspaceMember"),
    "MAValuation": ("financeops.modules.ma_workspace.models", "MAValuation"),
    "MADDItem": ("financeops.modules.ma_workspace.models", "MADDItem"),
    "MADocument": ("financeops.modules.ma_workspace.models", "MADocument"),
    "ModuleRegistry": ("financeops.modules.service_registry.models", "ModuleRegistry"),
    "TaskRegistry": ("financeops.modules.service_registry.models", "TaskRegistry"),
    "MarketplaceContributor": ("financeops.modules.marketplace.models", "MarketplaceContributor"),
    "MarketplaceTemplate": ("financeops.modules.marketplace.models", "MarketplaceTemplate"),
    "MarketplacePurchase": ("financeops.modules.marketplace.models", "MarketplacePurchase"),
    "MarketplacePayout": ("financeops.modules.marketplace.models", "MarketplacePayout"),
    "MarketplaceRating": ("financeops.modules.marketplace.models", "MarketplaceRating"),
    "WhiteLabelConfig": ("financeops.modules.white_label.models", "WhiteLabelConfig"),
    "WhiteLabelAuditLog": ("financeops.modules.white_label.models", "WhiteLabelAuditLog"),
    "PartnerProfile": ("financeops.modules.partner_program.models", "PartnerProfile"),
    "ReferralTracking": ("financeops.modules.partner_program.models", "ReferralTracking"),
    "PartnerCommission": ("financeops.modules.partner_program.models", "PartnerCommission"),
    "NotificationEvent": ("financeops.modules.notifications.models", "NotificationEvent"),
    "NotificationReadState": ("financeops.modules.notifications.models", "NotificationReadState"),
    "NotificationPreferences": ("financeops.modules.notifications.models", "NotificationPreferences"),
    "LearningSignal": ("financeops.modules.learning_engine.models", "LearningSignal"),
    "LearningCorrection": ("financeops.modules.learning_engine.models", "LearningCorrection"),
    "AIBenchmarkResult": ("financeops.modules.learning_engine.models", "AIBenchmarkResult"),
    "SearchIndexEntry": ("financeops.modules.search.models", "SearchIndexEntry"),
    "CashFlowForecastRun": ("financeops.modules.cash_flow_forecast.models", "CashFlowForecastRun"),
    "CashFlowForecastAssumption": ("financeops.modules.cash_flow_forecast.models", "CashFlowForecastAssumption"),
    "TaxProvisionRun": ("financeops.modules.tax_provision.models", "TaxProvisionRun"),
    "TaxPosition": ("financeops.modules.tax_provision.models", "TaxPosition"),
    "CovenantDefinition": ("financeops.modules.debt_covenants.models", "CovenantDefinition"),
    "CovenantBreachEvent": ("financeops.modules.debt_covenants.models", "CovenantBreachEvent"),
    "TPConfig": ("financeops.modules.transfer_pricing.models", "TPConfig"),
    "ICTransaction": ("financeops.modules.transfer_pricing.models", "ICTransaction"),
    "TransferPricingDoc": ("financeops.modules.transfer_pricing.models", "TransferPricingDoc"),
    "DirectorSignoff": ("financeops.modules.digital_signoff.models", "DirectorSignoff"),
    "StatutoryRegisterEntry": ("financeops.modules.statutory.models", "StatutoryRegisterEntry"),
    "StatutoryFiling": ("financeops.modules.statutory.models", "StatutoryFiling"),
    "MultiGAAPConfig": ("financeops.modules.multi_gaap.models", "MultiGAAPConfig"),
    "MultiGAAPRun": ("financeops.modules.multi_gaap.models", "MultiGAAPRun"),
    "AuditorPortalAccess": ("financeops.modules.auditor_portal.models", "AuditorPortalAccess"),
    "AuditorRequest": ("financeops.modules.auditor_portal.models", "AuditorRequest"),
    "MfaRecoveryCode": ("financeops.db.models.auth_tokens", "MfaRecoveryCode"),
    "PasswordResetToken": ("financeops.db.models.auth_tokens", "PasswordResetToken"),
    "AccountingJVAggregate": ("financeops.db.models.accounting_jv", "AccountingJVAggregate"),
    "AccountingJVLine": ("financeops.db.models.accounting_jv", "AccountingJVLine"),
    "AccountingJVStateEvent": ("financeops.db.models.accounting_jv", "AccountingJVStateEvent"),
    "AccountingJVApproval": ("financeops.db.models.accounting_approvals", "AccountingJVApproval"),
    "ApprovalSLATimer": ("financeops.db.models.accounting_approvals", "ApprovalSLATimer"),
    "AccountingVendor": ("financeops.db.models.accounting_vendor", "AccountingVendor"),
    "AccountingAttachment": ("financeops.db.models.accounting_vendor", "AccountingAttachment"),
    "ErpAttachmentLink": ("financeops.db.models.accounting_vendor", "ErpAttachmentLink"),
    "AccountingDuplicateFingerprint": (
        "financeops.db.models.accounting_vendor",
        "AccountingDuplicateFingerprint",
    ),
    "ErpAccountExternalRef": ("financeops.db.models.erp_sync", "ErpAccountExternalRef"),
    "AccountingGSTRule": ("financeops.db.models.accounting_tax", "AccountingGSTRule"),
    "AccountingTDSRule": ("financeops.db.models.accounting_tax", "AccountingTDSRule"),
    "AccountingTaxDeterminationLog": (
        "financeops.db.models.accounting_tax",
        "AccountingTaxDeterminationLog",
    ),
    "ErpPushRun": ("financeops.db.models.erp_push", "ErpPushRun"),
    "ErpPushEvent": ("financeops.db.models.erp_push", "ErpPushEvent"),
    "ErpPushIdempotencyKey": (
        "financeops.db.models.erp_push",
        "ErpPushIdempotencyKey",
    ),
    "ErpWebhookEvent": ("financeops.db.models.erp_webhook", "ErpWebhookEvent"),
    "AccountingInboundEmailMessage": (
        "financeops.db.models.accounting_ingestion",
        "AccountingInboundEmailMessage",
    ),
    "VendorPortalSubmission": (
        "financeops.db.models.accounting_ingestion",
        "VendorPortalSubmission",
    ),
    "AccountingNotificationEvent": (
        "financeops.db.models.accounting_notifications",
        "AccountingNotificationEvent",
    ),
    "ApprovalReminderRun": (
        "financeops.db.models.accounting_notifications",
        "ApprovalReminderRun",
    ),
    "AccountingAPAgeingSnapshot": (
        "financeops.db.models.accounting_notifications",
        "AccountingAPAgeingSnapshot",
    ),
    "AccountingAuditExportRun": (
        "financeops.db.models.accounting_notifications",
        "AccountingAuditExportRun",
    ),
}


def __getattr__(name: str) -> Any:
    target = _MODEL_IMPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = target
    module = import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value
