"""Phase 1E Platform Control Plane

Revision ID: 0008_phase1e_control_plane
Revises: 0007_phase1d3_lease_core
Create Date: 2026-03-07 00:00:00.000000
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from financeops.db.append_only import append_only_function_sql, create_trigger_sql, drop_trigger_sql

revision: str = "0008_phase1e_control_plane"
down_revision: str | None = "0007_phase1d3_lease_core"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

PLATFORM_DDL_STATEMENTS: tuple[str, ...] = (
    """CREATE TABLE cp_packages (
	package_code VARCHAR(64) NOT NULL, 
	package_name VARCHAR(255) NOT NULL, 
	version VARCHAR(32) NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	description VARCHAR(1024), 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (package_code)
)""",
    """CREATE INDEX idx_cp_packages_code ON cp_packages (package_code)""",
    """CREATE TABLE cp_module_registry (
	module_code VARCHAR(64) NOT NULL, 
	module_name VARCHAR(255) NOT NULL, 
	engine_context VARCHAR(64) NOT NULL, 
	is_financial_impacting BOOLEAN NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (module_code)
)""",
    """CREATE INDEX idx_cp_module_registry_engine ON cp_module_registry (engine_context)""",
    """CREATE TABLE cp_permissions (
	permission_code VARCHAR(128) NOT NULL, 
	resource_type VARCHAR(64) NOT NULL, 
	action VARCHAR(64) NOT NULL, 
	description VARCHAR(1024), 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (permission_code)
)""",
    """CREATE INDEX idx_cp_permissions_resource_action ON cp_permissions (resource_type, action)""",
    """CREATE TABLE cp_quota_policies (
	quota_type VARCHAR(64) NOT NULL, 
	window_type VARCHAR(16) NOT NULL, 
	window_seconds INTEGER NOT NULL, 
	default_max_value BIGINT NOT NULL, 
	default_enforcement_mode VARCHAR(16) NOT NULL, 
	description VARCHAR(1024), 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_quota_policy_type_window UNIQUE (quota_type, window_type)
)""",
    """CREATE INDEX idx_cp_quota_policy_type ON cp_quota_policies (quota_type)""",
    """CREATE TABLE cp_tenants (
	tenant_code VARCHAR(64) NOT NULL, 
	display_name VARCHAR(255) NOT NULL, 
	country_code VARCHAR(2) NOT NULL, 
	region VARCHAR(64) NOT NULL, 
	billing_tier VARCHAR(64) NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	correlation_id VARCHAR(64), 
	deactivated_at TIMESTAMP WITH TIME ZONE, 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_tenants_code UNIQUE (tenant_id, tenant_code)
)""",
    """CREATE INDEX idx_cp_tenants_tenant_created ON cp_tenants (tenant_id, created_at)""",
    """CREATE INDEX ix_cp_tenants_tenant_id ON cp_tenants (tenant_id)""",
    """CREATE TABLE cp_organisations (
	organisation_code VARCHAR(64) NOT NULL, 
	organisation_name VARCHAR(255) NOT NULL, 
	parent_organisation_id UUID, 
	supersedes_id UUID, 
	is_active BOOLEAN NOT NULL, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_org_code_created UNIQUE (tenant_id, organisation_code, created_at), 
	FOREIGN KEY(parent_organisation_id) REFERENCES cp_organisations (id) ON DELETE SET NULL, 
	FOREIGN KEY(supersedes_id) REFERENCES cp_organisations (id) ON DELETE SET NULL
)""",
    """CREATE INDEX idx_cp_org_tenant_parent ON cp_organisations (tenant_id, parent_organisation_id)""",
    """CREATE INDEX ix_cp_organisations_tenant_id ON cp_organisations (tenant_id)""",
    """CREATE TABLE cp_groups (
	group_code VARCHAR(64) NOT NULL, 
	group_name VARCHAR(255) NOT NULL, 
	organisation_id UUID NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_group_code UNIQUE (tenant_id, group_code), 
	FOREIGN KEY(organisation_id) REFERENCES cp_organisations (id) ON DELETE CASCADE
)""",
    """CREATE INDEX idx_cp_groups_org ON cp_groups (tenant_id, organisation_id)""",
    """CREATE INDEX ix_cp_groups_tenant_id ON cp_groups (tenant_id)""",
    """CREATE TABLE cp_entities (
	entity_code VARCHAR(64) NOT NULL, 
	entity_name VARCHAR(255) NOT NULL, 
	organisation_id UUID NOT NULL, 
	group_id UUID, 
	base_currency VARCHAR(3) NOT NULL, 
	country_code VARCHAR(2) NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	deactivated_at TIMESTAMP WITH TIME ZONE, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_entity_code UNIQUE (tenant_id, entity_code), 
	FOREIGN KEY(organisation_id) REFERENCES cp_organisations (id) ON DELETE RESTRICT, 
	FOREIGN KEY(group_id) REFERENCES cp_groups (id) ON DELETE SET NULL
)""",
    """CREATE INDEX idx_cp_entities_group ON cp_entities (tenant_id, group_id)""",
    """CREATE INDEX idx_cp_entities_org ON cp_entities (tenant_id, organisation_id)""",
    """CREATE INDEX ix_cp_entities_tenant_id ON cp_entities (tenant_id)""",
    """CREATE TABLE cp_user_organisation_assignments (
	user_id UUID NOT NULL, 
	organisation_id UUID NOT NULL, 
	is_primary BOOLEAN NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	effective_from TIMESTAMP WITH TIME ZONE NOT NULL, 
	effective_to TIMESTAMP WITH TIME ZONE, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_user_org_assignment_effective UNIQUE (tenant_id, user_id, organisation_id, effective_from), 
	FOREIGN KEY(user_id) REFERENCES iam_users (id) ON DELETE CASCADE, 
	FOREIGN KEY(organisation_id) REFERENCES cp_organisations (id) ON DELETE CASCADE
)""",
    """CREATE INDEX idx_cp_user_org_assignment_user ON cp_user_organisation_assignments (tenant_id, user_id, organisation_id)""",
    """CREATE INDEX ix_cp_user_organisation_assignments_tenant_id ON cp_user_organisation_assignments (tenant_id)""",
    """CREATE TABLE cp_user_entity_assignments (
	user_id UUID NOT NULL, 
	entity_id UUID NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	effective_from TIMESTAMP WITH TIME ZONE NOT NULL, 
	effective_to TIMESTAMP WITH TIME ZONE, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_user_entity_assignment_effective UNIQUE (tenant_id, user_id, entity_id, effective_from), 
	FOREIGN KEY(user_id) REFERENCES iam_users (id) ON DELETE CASCADE, 
	FOREIGN KEY(entity_id) REFERENCES cp_entities (id) ON DELETE CASCADE
)""",
    """CREATE INDEX idx_cp_user_entity_assignment_user ON cp_user_entity_assignments (tenant_id, user_id, entity_id)""",
    """CREATE INDEX ix_cp_user_entity_assignments_tenant_id ON cp_user_entity_assignments (tenant_id)""",
    """CREATE TABLE cp_tenant_package_assignments (
	package_id UUID NOT NULL, 
	assignment_status VARCHAR(32) NOT NULL, 
	effective_from TIMESTAMP WITH TIME ZONE NOT NULL, 
	effective_to TIMESTAMP WITH TIME ZONE, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_tenant_package_effective UNIQUE (tenant_id, package_id, effective_from), 
	FOREIGN KEY(package_id) REFERENCES cp_packages (id) ON DELETE RESTRICT
)""",
    """CREATE INDEX idx_cp_tenant_package_status ON cp_tenant_package_assignments (tenant_id, assignment_status, effective_from)""",
    """CREATE INDEX ix_cp_tenant_package_assignments_tenant_id ON cp_tenant_package_assignments (tenant_id)""",
    """CREATE TABLE cp_tenant_module_enablement (
	module_id UUID NOT NULL, 
	enabled BOOLEAN NOT NULL, 
	enablement_source VARCHAR(64) NOT NULL, 
	effective_from TIMESTAMP WITH TIME ZONE NOT NULL, 
	effective_to TIMESTAMP WITH TIME ZONE, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_tenant_module_enablement_effective UNIQUE (tenant_id, module_id, effective_from), 
	FOREIGN KEY(module_id) REFERENCES cp_module_registry (id) ON DELETE RESTRICT
)""",
    """CREATE INDEX idx_cp_tenant_module_enabled ON cp_tenant_module_enablement (tenant_id, module_id, enabled, effective_from)""",
    """CREATE INDEX ix_cp_tenant_module_enablement_tenant_id ON cp_tenant_module_enablement (tenant_id)""",
    """CREATE TABLE cp_module_feature_flags (
	module_id UUID NOT NULL, 
	flag_key VARCHAR(128) NOT NULL, 
	flag_value JSONB NOT NULL, 
	rollout_mode VARCHAR(16) NOT NULL, 
	compute_enabled BOOLEAN NOT NULL, 
	write_enabled BOOLEAN NOT NULL, 
	visibility_enabled BOOLEAN NOT NULL, 
	target_scope_type VARCHAR(16) NOT NULL, 
	target_scope_id UUID, 
	traffic_percent NUMERIC(5, 2), 
	effective_from TIMESTAMP WITH TIME ZONE NOT NULL, 
	effective_to TIMESTAMP WITH TIME ZONE, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_feature_flag_scope_effective UNIQUE (tenant_id, module_id, flag_key, target_scope_type, target_scope_id, effective_from), 
	FOREIGN KEY(module_id) REFERENCES cp_module_registry (id) ON DELETE RESTRICT
)""",
    """CREATE INDEX idx_cp_feature_flags_lookup ON cp_module_feature_flags (tenant_id, module_id, flag_key, effective_from)""",
    """CREATE INDEX ix_cp_module_feature_flags_tenant_id ON cp_module_feature_flags (tenant_id)""",
    """CREATE TABLE cp_roles (
	role_code VARCHAR(64) NOT NULL, 
	role_scope VARCHAR(32) NOT NULL, 
	inherits_role_id UUID, 
	is_active BOOLEAN NOT NULL, 
	description VARCHAR(1024), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_roles_code UNIQUE (tenant_id, role_code), 
	FOREIGN KEY(inherits_role_id) REFERENCES cp_roles (id) ON DELETE SET NULL
)""",
    """CREATE INDEX idx_cp_roles_scope ON cp_roles (tenant_id, role_scope, is_active)""",
    """CREATE INDEX ix_cp_roles_tenant_id ON cp_roles (tenant_id)""",
    """CREATE TABLE cp_role_permissions (
	role_id UUID NOT NULL, 
	permission_id UUID NOT NULL, 
	effect VARCHAR(8) NOT NULL, 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_role_permission UNIQUE (tenant_id, role_id, permission_id), 
	FOREIGN KEY(role_id) REFERENCES cp_roles (id) ON DELETE CASCADE, 
	FOREIGN KEY(permission_id) REFERENCES cp_permissions (id) ON DELETE RESTRICT
)""",
    """CREATE INDEX idx_cp_role_permissions_role ON cp_role_permissions (tenant_id, role_id)""",
    """CREATE INDEX ix_cp_role_permissions_tenant_id ON cp_role_permissions (tenant_id)""",
    """CREATE TABLE cp_user_role_assignments (
	user_id UUID NOT NULL, 
	role_id UUID NOT NULL, 
	context_type VARCHAR(32) NOT NULL, 
	context_id UUID, 
	is_active BOOLEAN NOT NULL, 
	effective_from TIMESTAMP WITH TIME ZONE NOT NULL, 
	effective_to TIMESTAMP WITH TIME ZONE, 
	assigned_by UUID, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_user_role_assignment_effective UNIQUE (tenant_id, user_id, role_id, context_type, context_id, effective_from), 
	FOREIGN KEY(user_id) REFERENCES iam_users (id) ON DELETE CASCADE, 
	FOREIGN KEY(role_id) REFERENCES cp_roles (id) ON DELETE CASCADE
)""",
    """CREATE INDEX idx_cp_user_role_assignment_lookup ON cp_user_role_assignments (tenant_id, user_id, context_type)""",
    """CREATE INDEX ix_cp_user_role_assignments_tenant_id ON cp_user_role_assignments (tenant_id)""",
    """CREATE TABLE cp_workflow_templates (
	template_code VARCHAR(128) NOT NULL, 
	module_id UUID NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	created_by UUID, 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_workflow_template_code UNIQUE (tenant_id, template_code), 
	FOREIGN KEY(module_id) REFERENCES cp_module_registry (id) ON DELETE RESTRICT
)""",
    """CREATE INDEX idx_cp_workflow_templates_module ON cp_workflow_templates (tenant_id, module_id)""",
    """CREATE INDEX ix_cp_workflow_templates_tenant_id ON cp_workflow_templates (tenant_id)""",
    """CREATE TABLE cp_workflow_template_versions (
	template_id UUID NOT NULL, 
	version_no INTEGER NOT NULL, 
	effective_from TIMESTAMP WITH TIME ZONE NOT NULL, 
	effective_to TIMESTAMP WITH TIME ZONE, 
	is_active BOOLEAN NOT NULL, 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_workflow_template_version UNIQUE (tenant_id, template_id, version_no), 
	CONSTRAINT uq_cp_workflow_template_effective UNIQUE (tenant_id, template_id, effective_from), 
	FOREIGN KEY(template_id) REFERENCES cp_workflow_templates (id) ON DELETE CASCADE
)""",
    """CREATE INDEX idx_cp_workflow_template_versions ON cp_workflow_template_versions (tenant_id, template_id, effective_from)""",
    """CREATE INDEX ix_cp_workflow_template_versions_tenant_id ON cp_workflow_template_versions (tenant_id)""",
    """CREATE TABLE cp_workflow_template_stages (
	template_version_id UUID NOT NULL, 
	stage_order INTEGER NOT NULL, 
	stage_code VARCHAR(128) NOT NULL, 
	stage_type VARCHAR(32) NOT NULL, 
	approval_mode VARCHAR(16) NOT NULL, 
	threshold_type VARCHAR(16) NOT NULL, 
	threshold_value INTEGER, 
	sla_hours INTEGER, 
	escalation_target_role_id UUID, 
	is_terminal BOOLEAN NOT NULL, 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_workflow_stage_order UNIQUE (tenant_id, template_version_id, stage_order), 
	FOREIGN KEY(template_version_id) REFERENCES cp_workflow_template_versions (id) ON DELETE CASCADE
)""",
    """CREATE INDEX idx_cp_workflow_template_stages_version ON cp_workflow_template_stages (tenant_id, template_version_id)""",
    """CREATE INDEX ix_cp_workflow_template_stages_tenant_id ON cp_workflow_template_stages (tenant_id)""",
    """CREATE TABLE cp_workflow_stage_role_map (
	stage_id UUID NOT NULL, 
	role_id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_stage_role_map UNIQUE (tenant_id, stage_id, role_id), 
	FOREIGN KEY(stage_id) REFERENCES cp_workflow_template_stages (id) ON DELETE CASCADE, 
	FOREIGN KEY(role_id) REFERENCES cp_roles (id) ON DELETE CASCADE
)""",
    """CREATE INDEX ix_cp_workflow_stage_role_map_tenant_id ON cp_workflow_stage_role_map (tenant_id)""",
    """CREATE TABLE cp_workflow_stage_user_map (
	stage_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_workflow_stage_user_map UNIQUE (tenant_id, stage_id, user_id), 
	FOREIGN KEY(stage_id) REFERENCES cp_workflow_template_stages (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES iam_users (id) ON DELETE CASCADE
)""",
    """CREATE INDEX ix_cp_workflow_stage_user_map_tenant_id ON cp_workflow_stage_user_map (tenant_id)""",
    """CREATE TABLE cp_workflow_instances (
	template_id UUID NOT NULL, 
	template_version_id UUID NOT NULL, 
	module_id UUID NOT NULL, 
	resource_type VARCHAR(64) NOT NULL, 
	resource_id UUID NOT NULL, 
	initiated_by UUID NOT NULL, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(template_id) REFERENCES cp_workflow_templates (id) ON DELETE RESTRICT, 
	FOREIGN KEY(template_version_id) REFERENCES cp_workflow_template_versions (id) ON DELETE RESTRICT, 
	FOREIGN KEY(module_id) REFERENCES cp_module_registry (id) ON DELETE RESTRICT
)""",
    """CREATE INDEX idx_cp_workflow_instances_tenant_created ON cp_workflow_instances (tenant_id, created_at)""",
    """CREATE INDEX ix_cp_workflow_instances_tenant_id ON cp_workflow_instances (tenant_id)""",
    """CREATE TABLE cp_workflow_stage_instances (
	workflow_instance_id UUID NOT NULL, 
	template_stage_id UUID NOT NULL, 
	stage_order INTEGER NOT NULL, 
	stage_code VARCHAR(128) NOT NULL, 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_workflow_stage_instance UNIQUE (tenant_id, workflow_instance_id, template_stage_id), 
	FOREIGN KEY(workflow_instance_id) REFERENCES cp_workflow_instances (id) ON DELETE CASCADE, 
	FOREIGN KEY(template_stage_id) REFERENCES cp_workflow_template_stages (id) ON DELETE RESTRICT
)""",
    """CREATE INDEX idx_cp_workflow_stage_instances ON cp_workflow_stage_instances (tenant_id, workflow_instance_id)""",
    """CREATE INDEX ix_cp_workflow_stage_instances_tenant_id ON cp_workflow_stage_instances (tenant_id)""",
    """CREATE TABLE cp_workflow_instance_events (
	workflow_instance_id UUID NOT NULL, 
	event_seq INTEGER NOT NULL, 
	event_type VARCHAR(64) NOT NULL, 
	event_time TIMESTAMP WITH TIME ZONE NOT NULL, 
	idempotency_key VARCHAR(128) NOT NULL, 
	metadata_json JSONB, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_workflow_instance_event_seq UNIQUE (tenant_id, workflow_instance_id, event_seq), 
	CONSTRAINT uq_cp_workflow_instance_event_idempotent UNIQUE (tenant_id, workflow_instance_id, event_type, idempotency_key), 
	FOREIGN KEY(workflow_instance_id) REFERENCES cp_workflow_instances (id) ON DELETE CASCADE
)""",
    """CREATE INDEX idx_cp_workflow_instance_events ON cp_workflow_instance_events (tenant_id, workflow_instance_id, event_seq)""",
    """CREATE INDEX ix_cp_workflow_instance_events_tenant_id ON cp_workflow_instance_events (tenant_id)""",
    """CREATE TABLE cp_workflow_stage_events (
	stage_instance_id UUID NOT NULL, 
	event_seq INTEGER NOT NULL, 
	event_type VARCHAR(64) NOT NULL, 
	event_time TIMESTAMP WITH TIME ZONE NOT NULL, 
	idempotency_key VARCHAR(128) NOT NULL, 
	metadata_json JSONB, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_workflow_stage_event_seq UNIQUE (tenant_id, stage_instance_id, event_seq), 
	CONSTRAINT uq_cp_workflow_stage_event_idempotent UNIQUE (tenant_id, stage_instance_id, event_type, idempotency_key), 
	FOREIGN KEY(stage_instance_id) REFERENCES cp_workflow_stage_instances (id) ON DELETE CASCADE
)""",
    """CREATE INDEX idx_cp_workflow_stage_events ON cp_workflow_stage_events (tenant_id, stage_instance_id, event_seq)""",
    """CREATE INDEX ix_cp_workflow_stage_events_tenant_id ON cp_workflow_stage_events (tenant_id)""",
    """CREATE TABLE cp_workflow_approvals (
	stage_instance_id UUID NOT NULL, 
	acted_by UUID NOT NULL, 
	decision VARCHAR(16) NOT NULL, 
	decision_reason VARCHAR(1024), 
	acted_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	delegated_from UUID, 
	idempotency_key VARCHAR(128) NOT NULL, 
	request_fingerprint VARCHAR(128) NOT NULL, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_workflow_approval_idempotent UNIQUE (tenant_id, stage_instance_id, acted_by, idempotency_key), 
	CONSTRAINT uq_cp_workflow_approval_fingerprint UNIQUE (tenant_id, stage_instance_id, request_fingerprint), 
	FOREIGN KEY(stage_instance_id) REFERENCES cp_workflow_stage_instances (id) ON DELETE CASCADE, 
	FOREIGN KEY(acted_by) REFERENCES iam_users (id) ON DELETE RESTRICT, 
	FOREIGN KEY(delegated_from) REFERENCES iam_users (id) ON DELETE SET NULL
)""",
    """CREATE INDEX idx_cp_workflow_approvals_stage ON cp_workflow_approvals (tenant_id, stage_instance_id, acted_at)""",
    """CREATE INDEX ix_cp_workflow_approvals_tenant_id ON cp_workflow_approvals (tenant_id)""",
    """CREATE TABLE cp_tenant_quota_assignments (
	quota_policy_id UUID, 
	quota_type VARCHAR(64) NOT NULL, 
	window_type VARCHAR(16) NOT NULL, 
	window_seconds INTEGER NOT NULL, 
	max_value BIGINT NOT NULL, 
	enforcement_mode VARCHAR(16) NOT NULL, 
	effective_from TIMESTAMP WITH TIME ZONE NOT NULL, 
	effective_to TIMESTAMP WITH TIME ZONE, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_tenant_quota_effective UNIQUE (tenant_id, quota_type, effective_from), 
	FOREIGN KEY(quota_policy_id) REFERENCES cp_quota_policies (id) ON DELETE SET NULL
)""",
    """CREATE INDEX idx_cp_tenant_quota_assignment ON cp_tenant_quota_assignments (tenant_id, quota_type, effective_from)""",
    """CREATE INDEX ix_cp_tenant_quota_assignments_tenant_id ON cp_tenant_quota_assignments (tenant_id)""",
    """CREATE TABLE cp_tenant_quota_usage_events (
	quota_type VARCHAR(64) NOT NULL, 
	usage_delta BIGINT NOT NULL, 
	operation_id UUID NOT NULL, 
	idempotency_key VARCHAR(128) NOT NULL, 
	request_fingerprint VARCHAR(128) NOT NULL, 
	source_layer VARCHAR(32) NOT NULL, 
	window_start TIMESTAMP WITH TIME ZONE NOT NULL, 
	window_end TIMESTAMP WITH TIME ZONE NOT NULL, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_quota_usage_idempotent UNIQUE (tenant_id, quota_type, operation_id, idempotency_key), 
	CONSTRAINT uq_cp_quota_usage_fingerprint_window UNIQUE (tenant_id, quota_type, request_fingerprint, window_start, window_end)
)""",
    """CREATE INDEX idx_cp_quota_usage_window ON cp_tenant_quota_usage_events (tenant_id, quota_type, window_start, window_end)""",
    """CREATE INDEX ix_cp_tenant_quota_usage_events_tenant_id ON cp_tenant_quota_usage_events (tenant_id)""",
    """CREATE TABLE cp_tenant_quota_windows (
	quota_type VARCHAR(64) NOT NULL, 
	window_start TIMESTAMP WITH TIME ZONE NOT NULL, 
	window_end TIMESTAMP WITH TIME ZONE NOT NULL, 
	consumed_value BIGINT NOT NULL, 
	last_event_id UUID NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_quota_window_unique UNIQUE (tenant_id, quota_type, window_start, window_end), 
	FOREIGN KEY(last_event_id) REFERENCES cp_tenant_quota_usage_events (id) ON DELETE RESTRICT
)""",
    """CREATE INDEX idx_cp_quota_window_lookup ON cp_tenant_quota_windows (tenant_id, quota_type, window_end)""",
    """CREATE INDEX ix_cp_tenant_quota_windows_tenant_id ON cp_tenant_quota_windows (tenant_id)""",
    """CREATE TABLE cp_tenant_isolation_policy (
	isolation_tier VARCHAR(16) NOT NULL, 
	db_cluster VARCHAR(128) NOT NULL, 
	schema_name VARCHAR(128) NOT NULL, 
	worker_pool VARCHAR(128) NOT NULL, 
	region VARCHAR(64) NOT NULL, 
	migration_state VARCHAR(32) NOT NULL, 
	route_version INTEGER NOT NULL, 
	effective_from TIMESTAMP WITH TIME ZONE NOT NULL, 
	effective_to TIMESTAMP WITH TIME ZONE, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_isolation_route_version UNIQUE (tenant_id, route_version), 
	CONSTRAINT uq_cp_isolation_effective UNIQUE (tenant_id, effective_from)
)""",
    """CREATE INDEX idx_cp_isolation_lookup ON cp_tenant_isolation_policy (tenant_id, migration_state, route_version)""",
    """CREATE INDEX ix_cp_tenant_isolation_policy_tenant_id ON cp_tenant_isolation_policy (tenant_id)""",
    """CREATE TABLE cp_tenant_migration_events (
	isolation_policy_id VARCHAR(128) NOT NULL, 
	route_version INTEGER NOT NULL, 
	event_seq INTEGER NOT NULL, 
	event_type VARCHAR(64) NOT NULL, 
	event_time TIMESTAMP WITH TIME ZONE NOT NULL, 
	idempotency_key VARCHAR(128) NOT NULL, 
	metadata_json JSONB, 
	correlation_id VARCHAR(64), 
	tenant_id UUID NOT NULL, 
	chain_hash VARCHAR(64) NOT NULL, 
	previous_hash VARCHAR(64) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cp_tenant_migration_seq UNIQUE (tenant_id, route_version, event_seq), 
	CONSTRAINT uq_cp_tenant_migration_idempotent UNIQUE (tenant_id, route_version, event_type, idempotency_key)
)""",
    """CREATE INDEX idx_cp_tenant_migration_events ON cp_tenant_migration_events (tenant_id, route_version, event_seq)""",
    """CREATE INDEX ix_cp_tenant_migration_events_tenant_id ON cp_tenant_migration_events (tenant_id)""",
)

GLOBAL_TABLES: tuple[str, ...] = (
    "cp_packages",
    "cp_module_registry",
    "cp_permissions",
    "cp_quota_policies",
)

TENANT_TABLES: tuple[str, ...] = (
    "cp_tenants",
    "cp_organisations",
    "cp_groups",
    "cp_entities",
    "cp_user_organisation_assignments",
    "cp_user_entity_assignments",
    "cp_tenant_package_assignments",
    "cp_tenant_module_enablement",
    "cp_module_feature_flags",
    "cp_roles",
    "cp_role_permissions",
    "cp_user_role_assignments",
    "cp_workflow_templates",
    "cp_workflow_template_versions",
    "cp_workflow_template_stages",
    "cp_workflow_stage_role_map",
    "cp_workflow_stage_user_map",
    "cp_workflow_instances",
    "cp_workflow_stage_instances",
    "cp_workflow_instance_events",
    "cp_workflow_stage_events",
    "cp_workflow_approvals",
    "cp_tenant_quota_assignments",
    "cp_tenant_quota_usage_events",
    "cp_tenant_quota_windows",
    "cp_tenant_isolation_policy",
    "cp_tenant_migration_events",
)

DROP_ORDER: tuple[str, ...] = (
    "cp_tenant_migration_events",
    "cp_tenant_isolation_policy",
    "cp_tenant_quota_windows",
    "cp_tenant_quota_usage_events",
    "cp_tenant_quota_assignments",
    "cp_workflow_approvals",
    "cp_workflow_stage_events",
    "cp_workflow_instance_events",
    "cp_workflow_stage_instances",
    "cp_workflow_instances",
    "cp_workflow_stage_user_map",
    "cp_workflow_stage_role_map",
    "cp_workflow_template_stages",
    "cp_workflow_template_versions",
    "cp_workflow_templates",
    "cp_user_role_assignments",
    "cp_role_permissions",
    "cp_roles",
    "cp_module_feature_flags",
    "cp_tenant_module_enablement",
    "cp_tenant_package_assignments",
    "cp_user_entity_assignments",
    "cp_user_organisation_assignments",
    "cp_entities",
    "cp_groups",
    "cp_organisations",
    "cp_tenants",
    "cp_quota_policies",
    "cp_permissions",
    "cp_module_registry",
    "cp_packages",
)


def _execute_frozen_ddl() -> None:
    for statement in PLATFORM_DDL_STATEMENTS:
        op.execute(statement)


def _enable_tenant_rls() -> None:
    for table_name in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table_name}_tenant_isolation
              ON {table_name}
              USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)
            """
        )


def _apply_append_only() -> None:
    op.execute(append_only_function_sql())
    for table_name in TENANT_TABLES:
        op.execute(drop_trigger_sql(table_name))
        op.execute(create_trigger_sql(table_name))


def _drop_append_only() -> None:
    for table_name in DROP_ORDER:
        if table_name in TENANT_TABLES:
            op.execute(drop_trigger_sql(table_name))


def upgrade() -> None:
    _execute_frozen_ddl()
    _enable_tenant_rls()
    _apply_append_only()


def downgrade() -> None:
    _drop_append_only()
    for table_name in DROP_ORDER:
        op.drop_table(table_name)
