from __future__ import annotations

MISSING_LOCKED_RATE = "MISSING_LOCKED_RATE"
LINEAGE_INCOMPLETE = "LINEAGE_INCOMPLETE"
INVALID_EVENT_SEQUENCE = "INVALID_EVENT_SEQUENCE"
VERSION_CHAIN_BROKEN = "VERSION_CHAIN_BROKEN"
DUPLICATE_IDEMPOTENT_REQUEST = "DUPLICATE_IDEMPOTENT_REQUEST"

ACCOUNTING_ERROR_CODES: tuple[str, ...] = (
    MISSING_LOCKED_RATE,
    LINEAGE_INCOMPLETE,
    INVALID_EVENT_SEQUENCE,
    VERSION_CHAIN_BROKEN,
    DUPLICATE_IDEMPOTENT_REQUEST,
)


